function db_ERA5_data_retrieval(siteID,dateStart,dateEnd,biometPath,type)
%==========================================================================
% The function downloads hourly ERA5 land data by calling the CDS API using
%   one of two Python scripts (ERA5_EC_pipeline_ts.py or 
%   ERA5_EC_pipeline.py).
% The following variables are downloaded by default when type='ts': (1) 2-m 
%   dew point temperature; (2) 2-m air temperature; (3) surface incoming 
%   solar radiation; (4) surface pressure; and (5) total precipitation. 
%   This could be modified so that the Python script accepts an optional 
%   input for alternate/additional variables.
% Time-series optimized data does not exist for the boundary layer height 
%   variable, so it has to be downloaded by specifying
%   type='boundary_layer_height'.
%
% Example(s):
% --> Command line for time-series optimized data
% db_ERA5_data_retrieval('DSM','2024-01-01','2025-12-31')
%
% --> Command line for boundary layer height. It is downloaded as a spatial
%       data set which is a much slower API process.
% db_ERA5_data_retrieval('DSM','2024-01-01','2025-12-31','boundary_layer_height')
%
%==========================================================================

biomet_folder = 'Biomet.net';

file_path = fileparts(which('db_ERA5_data_retrieval'));
path_parts = regexp(file_path,filesep,'split');
idx = find(contains(path_parts,biomet_folder));
if ispc
    root_pth = fullfile(path_parts{1:idx});
    % root_pth = sprintf("%s%s%s",path_parts{1},pth_sep,path_parts{2});
elseif ismac
    root_pth = fullfile(pth_sep,path_parts{1:idx});
end

% Default is to pull the past year of data
tmp = today; %#ok<TTDAY1>
arg_default('dateStart',char(datetime(tmp-366,'convertfrom','datenum','format','yyyy-MM-dd'))); %#ok<*DATST>
arg_default('dateEnd',char(datetime(tmp-366,'convertfrom','datenum','format','yyyy-MM-dd')));
arg_default('biometPath',root_pth)
arg_default('type','ts')

% Save raw ERA5 data to temporary directory
if strcmp(tempdir,'/tmp') & ~ispc
    % /var/tmp is not cleared on reboot
    pathToMatlabTemp = fullfile('/var/tmp','MatlabTemp',siteID);
else
    pathToMatlabTemp = fullfile(tempdir,'MatlabTemp',siteID);
end
if ~exist(pathToMatlabTemp,'dir')
    mkdir(pathToMatlabTemp);
end

% The 'ts' option downloads an API optimized time series for a single 
%   location from the ERA5 dataset. The 'ts' option is much faster than a
%   call to the "reanalysis-era5-land" spatial dataset.
if strcmp(type,'ts')
    pathToPythonScript = fullfile(biometPath,'Python','ERA5_EC_pipeline_ts.py');
else
    pathToPythonScript = fullfile(biometPath,'Python','ERA5_EC_pipeline.py');
end

% Path for siteID.yml
path_yml = fullfile(biomet_database_default,'Calculation_Procedures',...
    'TraceAnalysis_ini',siteID,char([siteID '_config.yml']));

if ~isfile(path_yml)
    fprintf('Could not find: %s\n',path_yml)
    disp('Aborting ERA5 data retrieval!')
    return
end

% Retrieve lat-lon from siteID.yml file
yml_data = yaml.loadFile(path_yml);

lat = [];
lon = [];

if isfield(yml_data,'Metadata')
    if isfield(yml_data.Metadata,'lat') && isfield(yml_data.Metadata,'long')
        lat = yml_data.Metadata.lat;
        lon = yml_data.Metadata.long;
    end
end

if isempty(lat) | isempty(lon)
    disp('Missing metadata. Check that lat and long are specified in the _config.yml file.')
    disp('Aborting ERA5 data retrieval!')
    return
end

% Make sure that the lat-lon location corresponds with a ERA5-land land-sea
%   mask value greater than 80%. Lower values can sometimes return NaN
load('ERA5_land_static.mat','data')

% Construct latitude and longitude matrix as 10× lsm grid spacing of
%   0.1°×0.1°
lon_era5 = int16((0:3599)');
lat_era5 = int16((900:-1:-900)');
[lon_era5,lat_era5] = ndgrid(lon_era5,lat_era5);

lon_site = int16(10.*lon);
lon_adj = 0;
if lon_site<0
    lon_site = 3600 + lon_site;
    lon_adj = -360;
end
lat_site = int16(10.*lat);

% Find location of site lat-lon in matrix
minPoint = abs(lon_era5-lon_site) + abs(lat_era5-lat_site);
[r,c] = find(minPoint==0,1,'first');

if data.lsm(r,c)<80
    fprintf(char([' Land-sea mask < 80%% (lsm=%i). Selecting alternate near-by point.\n',...
        ' Original location: %3.1f (lat) %3.1f (lon)\n',...
        ' Original elevation: %i m\n']),...
        data.lsm(r,c),lat,lon,data.z(r,c));


    % Find closest point with value greater than 80
    lon_ROI = lon_era5((r-5):(r+5),(c-5):(c+5));
    lat_ROI = lat_era5((r-5):(r+5),(c-5):(c+5));
    lsm_ROI = data.lsm((r-5):(r+5),(c-5):(c+5));
    elev_ROI = data.z((r-5):(r+5),(c-5):(c+5));

    % Convert coordinates to distance from site lat-lon
    dist = hypot(double(lon_ROI-lon_site), double(lat_ROI-lat_site));
    
    % Find lsm in region of interest which are greater than 80
    idx = lsm_ROI>80;

    if sum(idx(:))>0
        dist(~idx) = NaN;
    
        % Points in the region of interest which are closest to the site
        %   lat-lon and have an lsm greater than 80
        minDist = dist==min(dist(:));
        [r,c] = find(minDist==1);
    
        % Since multiple results are equi-distant, take the first
        lat = double(lat_ROI(r(1),c(1)))./10;
        lon = double(lon_ROI(r(1),c(1)))./10;
        lon = lon + lon_adj;
    
        fprintf(' New location: %3.1f (lat) %3.1f (lon)\n New elevation: %i m\n',...
            lat,lon,elev_ROI(r(1),c(1)))
    else
        disp('No near-by suitable locations found. Attempting to retrieve data for original location.')
    end
end

%% Run API request for ERA5 download
%--> Retrieves hourly ERA5 data in one month batches

if strcmp(type,'ts')
    % Input argument order:
    % [0] script; [1] start date; [2] end date; [3] latitude;
    %   [4] longitude; [5] output directory
    
    % Python script uses CDS API
    cmd_str = sprintf('"%s" %s %s %3.1f %3.1f "%s"',pathToPythonScript,...
        dateStart, dateEnd, lat, lon, pathToMatlabTemp);

else
    % Input argument order:
    % [0] script; [1] start year; [2] end year; [3] start month; [4] end month
    %   [5] latitude; [6] longitude; [7] output directory
    
    [yearStart,mnthStart,~] = datevec(dateStart);
    [yearEnd,mnthEnd,~] = datevec(dateEnd);
    
    if strcmp(type,'spatial')
        % Python script uses CDS API
        cmd_str = sprintf('"%s" %d %d %d %d %3.4f %3.4f "%s"',pathToPythonScript,yearStart,...
            yearEnd,mnthStart,mnthEnd, lat, lon, pathToMatlabTemp);
    else
        % Get list of ERA5 variables
        varList = getVarList;

        if sum(matches(varList.hourly_land,type))==1
            ERA5_dataset = 'reanalysis-era5-land';
        elseif sum(matches(varList.hourly_singleLvl,type))==1
            ERA5_dataset = 'reanalysis-era5-single-levels';
        else
            fprintf(' *** Variable %s not found in ERA5 variable list ***\n Aborting ERA5 API request!\n',type)
            return
        end

        % Call to Python script, passing variable name for a single variable
        cmd_str = sprintf('"%s" %d %d %d %d %3.4f %3.4f "%s" %s %s',pathToPythonScript,yearStart,...
            yearEnd,mnthStart,mnthEnd, lat, lon, pathToMatlabTemp,type,ERA5_dataset);
    end
end

pyrunfile(cmd_str);

%% Extract and rename .zip files
% The 'ts' dataset can only be downloaded as .zip files

if strcmp(type,'ts')
    varStr = {'2m_dewpoint_temperature','2m_temperature',...
            'surface_solar_radiation_downwards','surface_pressure',...
            'total_precipitation'};
    
    for i=1:length(varStr)
        pathToZipFile = fullfile(pathToMatlabTemp,char([varStr{i} '.zip']));
    
        if isfile(pathToZipFile)
            % Unzip ERA data
            file2rename = unzip(pathToZipFile,pathToMatlabTemp);
    
            % Rename .nc file
            dest = fullfile(pathToMatlabTemp,char([varStr{i} '.nc']));
            movefile(file2rename{1},dest)
            
            % Delete .zip file
            delete(pathToZipFile)
        end
    end
end

end

function varList = getVarList

varList.hourly_land = [...
        "2m_dewpoint_temperature",...
        "2m_temperature",...
        "skin_temperature",...
        "soil_temperature_level_1",...
        "soil_temperature_level_2",...
        "soil_temperature_level_3",...
        "soil_temperature_level_4",...
        "lake_bottom_temperature",...
        "lake_ice_depth",...
        "lake_ice_temperature",...
        "lake_mix_layer_depth",...
        "lake_mix_layer_temperature",...
        "lake_shape_factor",...
        "lake_total_layer_temperature",...
        "snow_albedo",...
        "snow_cover",...
        "snow_density",...
        "snow_depth",...
        "snow_depth_water_equivalent",...
        "snowfall",...
        "snowmelt",...
        "temperature_of_snow_layer",...
        "skin_reservoir_content",...
        "volumetric_soil_water_layer_1",...
        "volumetric_soil_water_layer_2",...
        "volumetric_soil_water_layer_3",...
        "volumetric_soil_water_layer_4",...
        "forecast_albedo",...
        "surface_latent_heat_flux",...
        "surface_net_solar_radiation",...
        "surface_net_thermal_radiation",...
        "surface_sensible_heat_flux",...
        "surface_solar_radiation_downwards",...
        "surface_thermal_radiation_downwards",...
        "evaporation_from_bare_soil",...
        "evaporation_from_open_water_surfaces_excluding_oceans",...
        "evaporation_from_the_top_of_canopy",...
        "evaporation_from_vegetation_transpiration",...
        "potential_evaporation",...
        "runoff",...
        "snow_evaporation",...
        "sub_surface_runoff",...
        "surface_runoff",...
        "total_evaporation",...
        "10m_u_component_of_wind",...
        "10m_v_component_of_wind",...
        "surface_pressure",...
        "total_precipitation",...
        "leaf_area_index_high_vegetation",...
        "leaf_area_index_low_vegetation",...
        "high_vegetation_cover",...
        "glacier_mask",...
        "lake_cover",...
        "low_vegetation_cover",...
        "lake_total_depth",...
        "geopotential",...
        "land_sea_mask",...
        "soil_type",...
        "type_of_high_vegetation",...
        "type_of_low_vegetation"];

varList.hourly_singleLvl = [...
        "10m_u_component_of_wind",...
        "10m_v_component_of_wind",...
        "2m_dewpoint_temperature",...
        "2m_temperature",...
        "mean_sea_level_pressure",...
        "mean_wave_direction",...
        "mean_wave_period",...
        "sea_surface_temperature",...
        "significant_height_of_combined_wind_waves_and_swell",...
        "surface_pressure",...
        "total_precipitation",...
        "ice_temperature_layer_1",...
        "ice_temperature_layer_2",...
        "ice_temperature_layer_3",...
        "ice_temperature_layer_4",...
        "maximum_2m_temperature_since_previous_post_processing",...
        "minimum_2m_temperature_since_previous_post_processing",...
        "skin_temperature",...
        "100m_u_component_of_wind",...
        "100m_v_component_of_wind",...
        "10m_u_component_of_neutral_wind",...
        "10m_v_component_of_neutral_wind",...
        "10m_wind_gust_since_previous_post_processing",...
        "instantaneous_10m_wind_gust",...
        "mean_boundary_layer_dissipation",...
        "mean_convective_precipitation_rate",...
        "mean_convective_snowfall_rate",...
        "mean_eastward_gravity_wave_surface_stress",...
        "mean_eastward_turbulent_surface_stress",...
        "mean_evaporation_rate",...
        "mean_gravity_wave_dissipation",...
        "mean_large_scale_precipitation_fraction",...
        "mean_large_scale_precipitation_rate",...
        "mean_large_scale_snowfall_rate",...
        "mean_northward_gravity_wave_surface_stress",...
        "mean_northward_turbulent_surface_stress",...
        "mean_potential_evaporation_rate",...
        "mean_runoff_rate",...
        "mean_snow_evaporation_rate",...
        "mean_snowfall_rate",...
        "mean_snowmelt_rate",...
        "mean_sub_surface_runoff_rate",...
        "mean_surface_direct_short_wave_radiation_flux",...
        "mean_surface_direct_short_wave_radiation_flux_clear_sky",...
        "mean_surface_downward_long_wave_radiation_flux",...
        "mean_surface_downward_long_wave_radiation_flux_clear_sky",...
        "mean_surface_downward_short_wave_radiation_flux",...
        "mean_surface_downward_short_wave_radiation_flux_clear_sky",...
        "mean_surface_downward_uv_radiation_flux",...
        "mean_surface_latent_heat_flux",...
        "mean_surface_net_long_wave_radiation_flux",...
        "mean_surface_net_long_wave_radiation_flux_clear_sky",...
        "mean_surface_net_short_wave_radiation_flux",...
        "mean_surface_net_short_wave_radiation_flux_clear_sky",...
        "mean_surface_runoff_rate",...
        "mean_surface_sensible_heat_flux",...
        "mean_top_downward_short_wave_radiation_flux",...
        "mean_top_net_long_wave_radiation_flux",...
        "mean_top_net_long_wave_radiation_flux_clear_sky",...
        "mean_top_net_short_wave_radiation_flux",...
        "mean_top_net_short_wave_radiation_flux_clear_sky",...
        "mean_total_precipitation_rate",...
        "mean_vertically_integrated_moisture_divergence",...
        "clear_sky_direct_solar_radiation_at_surface",...
        "downward_uv_radiation_at_the_surface",...
        "forecast_logarithm_of_surface_roughness_for_heat",...
        "instantaneous_surface_sensible_heat_flux",...
        "near_ir_albedo_for_diffuse_radiation",...
        "near_ir_albedo_for_direct_radiation",...
        "surface_latent_heat_flux",...
        "surface_net_solar_radiation",...
        "surface_net_solar_radiation_clear_sky",...
        "surface_net_thermal_radiation",...
        "surface_net_thermal_radiation_clear_sky",...
        "surface_sensible_heat_flux",...
        "surface_solar_radiation_downward_clear_sky",...
        "surface_solar_radiation_downwards",...
        "surface_thermal_radiation_downward_clear_sky",...
        "surface_thermal_radiation_downwards",...
        "toa_incident_solar_radiation",...
        "top_net_solar_radiation",...
        "top_net_solar_radiation_clear_sky",...
        "top_net_thermal_radiation",...
        "top_net_thermal_radiation_clear_sky",...
        "total_sky_direct_solar_radiation_at_surface",...
        "uv_visible_albedo_for_diffuse_radiation",...
        "uv_visible_albedo_for_direct_radiation",...
        "cloud_base_height",...
        "high_cloud_cover",...
        "low_cloud_cover",...
        "medium_cloud_cover",...
        "total_cloud_cover",...
        "total_column_cloud_ice_water",...
        "total_column_cloud_liquid_water",...
        "vertical_integral_of_divergence_of_cloud_frozen_water_flux",...
        "vertical_integral_of_divergence_of_cloud_liquid_water_flux",...
        "vertical_integral_of_eastward_cloud_frozen_water_flux",...
        "vertical_integral_of_eastward_cloud_liquid_water_flux",...
        "vertical_integral_of_northward_cloud_frozen_water_flux",...
        "vertical_integral_of_northward_cloud_liquid_water_flux",...
        "lake_bottom_temperature",...
        "lake_cover",...
        "lake_depth",...
        "lake_ice_depth",...
        "lake_ice_temperature",...
        "lake_mix_layer_depth",...
        "lake_mix_layer_temperature",...
        "lake_shape_factor",...
        "lake_total_layer_temperature",...
        "evaporation",...
        "potential_evaporation",...
        "runoff",...
        "sub_surface_runoff",...
        "surface_runoff",...
        "convective_precipitation",...
        "convective_rain_rate",...
        "instantaneous_large_scale_surface_precipitation_fraction",...
        "large_scale_rain_rate",...
        "large_scale_precipitation",...
        "large_scale_precipitation_fraction",...
        "maximum_total_precipitation_rate_since_previous_post_processing",...
        "minimum_total_precipitation_rate_since_previous_post_processing",...
        "precipitation_type",...
        "total_column_rain_water",...
        "convective_snowfall",...
        "convective_snowfall_rate_water_equivalent",...
        "large_scale_snowfall_rate_water_equivalent",...
        "large_scale_snowfall",...
        "snow_albedo",...
        "snow_density",...
        "snow_depth",...
        "snow_evaporation",...
        "snowfall",...
        "snowmelt",...
        "temperature_of_snow_layer",...
        "total_column_snow_water",...
        "soil_temperature_level_1",...
        "soil_temperature_level_2",...
        "soil_temperature_level_3",...
        "soil_temperature_level_4",...
        "soil_type",...
        "volumetric_soil_water_layer_1",...
        "volumetric_soil_water_layer_2",...
        "volumetric_soil_water_layer_3",...
        "volumetric_soil_water_layer_4",...
        "vertical_integral_of_divergence_of_geopotential_flux",...
        "vertical_integral_of_divergence_of_kinetic_energy_flux",...
        "vertical_integral_of_divergence_of_mass_flux",...
        "vertical_integral_of_divergence_of_moisture_flux",...
        "vertical_integral_of_divergence_of_ozone_flux",...
        "vertical_integral_of_divergence_of_thermal_energy_flux",...
        "vertical_integral_of_divergence_of_total_energy_flux",...
        "vertical_integral_of_eastward_geopotential_flux",...
        "vertical_integral_of_eastward_heat_flux",...
        "vertical_integral_of_eastward_kinetic_energy_flux",...
        "vertical_integral_of_eastward_mass_flux",...
        "vertical_integral_of_eastward_ozone_flux",...
        "vertical_integral_of_eastward_total_energy_flux",...
        "vertical_integral_of_eastward_water_vapour_flux",...
        "vertical_integral_of_energy_conversion",...
        "vertical_integral_of_kinetic_energy",...
        "vertical_integral_of_mass_of_atmosphere",...
        "vertical_integral_of_mass_tendency",...
        "vertical_integral_of_northward_geopotential_flux",...
        "vertical_integral_of_northward_heat_flux",...
        "vertical_integral_of_northward_kinetic_energy_flux",...
        "vertical_integral_of_northward_mass_flux",...
        "vertical_integral_of_northward_ozone_flux",...
        "vertical_integral_of_northward_total_energy_flux",...
        "vertical_integral_of_northward_water_vapour_flux",...
        "vertical_integral_of_potential_and_internal_energy",...
        "vertical_integral_of_potential_internal_and_latent_energy",...
        "vertical_integral_of_temperature",...
        "vertical_integral_of_thermal_energy",...
        "vertical_integral_of_total_energy",...
        "vertically_integrated_moisture_divergence",...
        "high_vegetation_cover",...
        "leaf_area_index_high_vegetation",...
        "leaf_area_index_low_vegetation",...
        "low_vegetation_cover",...
        "type_of_high_vegetation",...
        "type_of_low_vegetation",...
        "air_density_over_the_oceans",...
        "coefficient_of_drag_with_waves",...
        "free_convective_velocity_over_the_oceans",...
        "maximum_individual_wave_height",...
        "mean_direction_of_total_swell",...
        "mean_direction_of_wind_waves",...
        "mean_period_of_total_swell",...
        "mean_period_of_wind_waves",...
        "mean_square_slope_of_waves",...
        "mean_wave_direction_of_first_swell_partition",...
        "mean_wave_direction_of_second_swell_partition",...
        "mean_wave_direction_of_third_swell_partition",...
        "mean_wave_period_based_on_first_moment",...
        "mean_wave_period_based_on_first_moment_for_swell",...
        "mean_wave_period_based_on_first_moment_for_wind_waves",...
        "mean_wave_period_based_on_second_moment_for_swell",...
        "mean_wave_period_based_on_second_moment_for_wind_waves",...
        "mean_wave_period_of_first_swell_partition",...
        "mean_wave_period_of_second_swell_partition",...
        "mean_wave_period_of_third_swell_partition",...
        "mean_zero_crossing_wave_period",...
        "model_bathymetry",...
        "normalized_energy_flux_into_ocean",...
        "normalized_energy_flux_into_waves",...
        "normalized_stress_into_ocean",...
        "ocean_surface_stress_equivalent_10m_neutral_wind_direction",...
        "ocean_surface_stress_equivalent_10m_neutral_wind_speed",...
        "peak_wave_period",...
        "period_corresponding_to_maximum_individual_wave_height",...
        "significant_height_of_total_swell",...
        "significant_height_of_wind_waves",...
        "significant_wave_height_of_first_swell_partition",...
        "significant_wave_height_of_second_swell_partition",...
        "significant_wave_height_of_third_swell_partition",...
        "wave_spectral_directional_width",...
        "wave_spectral_directional_width_for_swell",...
        "wave_spectral_directional_width_for_wind_waves",...
        "wave_spectral_kurtosis",...
        "wave_spectral_peakedness",...
        "wave_spectral_skewness",...
        "angle_of_sub_gridscale_orography",...
        "anisotropy_of_sub_gridscale_orography",...
        "benjamin_feir_index",...
        "boundary_layer_dissipation",...
        "boundary_layer_height",...
        "charnock",...
        "convective_available_potential_energy",...
        "convective_inhibition",...
        "duct_base_height",...
        "eastward_gravity_wave_surface_stress",...
        "eastward_turbulent_surface_stress",...
        "forecast_albedo",...
        "forecast_surface_roughness",...
        "friction_velocity",...
        "geopotential",...
        "gravity_wave_dissipation",...
        "instantaneous_eastward_turbulent_surface_stress",...
        "instantaneous_moisture_flux",...
        "instantaneous_northward_turbulent_surface_stress",...
        "k_index",...
        "land_sea_mask",...
        "mean_vertical_gradient_of_refractivity_inside_trapping_layer",...
        "minimum_vertical_gradient_of_refractivity_inside_trapping_layer",...
        "northward_gravity_wave_surface_stress",...
        "northward_turbulent_surface_stress",...
        "sea_ice_cover",...
        "skin_reservoir_content",...
        "slope_of_sub_gridscale_orography",...
        "standard_deviation_of_filtered_subgrid_orography",...
        "standard_deviation_of_orography",...
        "total_column_ozone",...
        "total_column_supercooled_liquid_water",...
        "total_column_water",...
        "total_column_water_vapour",...
        "total_totals_index",...
        "trapping_layer_base_height",...
        "trapping_layer_top_height",...
        "u_component_stokes_drift",...
        "v_component_stokes_drift",...
        "zero_degree_level"];

varList.short.hourly_singleLvl = [...
    
    ];
end